FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY worker.py .

# Exponemos el puerto 8001 (que usas en tu código por defecto)
EXPOSE 8001

CMD ["uvicorn", "worker:app", "--host", "0.0.0.0", "--port", "8001"]